# Generated by Django 3.1.2 on 2020-11-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201029_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(default='https://repairsyourself.ru/wp-content/uploads/2020/03/404.png', verbose_name='Ссылка на картинку'),
        ),
    ]
